# Generated by Django 4.0.1 on 2022-03-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementbid',
            options={'ordering': ['-placementbid_modified']},
        ),
        migrations.RemoveField(
            model_name='placementbid',
            name='shares',
        ),
    ]
