# Generated by Django 4.0.1 on 2022-04-06 03:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_placement_placement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='placement_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
